name: Zlak
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74557
title: 'Entrepreneur, Consultant & Geek '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#beb8b4'
    - '#241e1b'
    - '#ff0000'
    - '#b36149'
  brandStrength: 0.5
  lightness: 0.4484138728585094
  saturation: 0.8552811883855611
  rhythmicContrast: 0.4807859866414219
purpose: []
